spring:
  application:
    name: bookstore-spring
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: none


  datasource:
    url: ${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver


server:
  port: 8065


logging:
  level:
    '[com.edvin.projects.bookstore.BookstoreSpringApplication]': 
